### ISSUE TITLE
[Feature request] Long press on search button opens directly the search filters

### ISSUE THREAD

**Issue by Palloxin** [rev0lgenX/AniLib#45]
![IMG_20220503_115111](https://user-images.githubusercontent.com/75091899/166434349-0f997fb1-582c-4fb9-be51-2521d95a7dd2.jpg)
long pressing this button should make the option filters appear directly instead of the normal 2 step. Also i ask if you can make the appearance of the option filter faster, it is a bit slow compared to other feature. it is used quite a bit so the speed of its appearance should be improved.
This feature would be quite good and popular if implemented but it is an hidden one so i suggest to add a tutorial or something similar. for example the first time an user clicks the search button tge app should show the user the existence of this shortcut.

**Comment by rev0lgenX** [comment]
Did you install the snapshot app and tried to open search from there?

**Comment by Palloxin** [comment]
yes

**Comment by rev0lgenX** [comment]
Is it still slow?

**Comment by Palloxin** [comment]
iyes

**Comment by natsuthelight** [comment]
The idea of ​​adding the filter option after a long press on the search button, I find that it is not too useful. Because the time to do a long press or do the 2 steps will be exactly the same. But if instead of putting exactly the same filter option, we put a much simplified version of the filter option, that would be a good idea.
Like after a long press, it directly offers us the choice between "Upcoming", "Top 100", "Seasonal" etc...

and for the idea of ​​the tutorial, if you could also add the choice of theme.

@Palloxin @rev0lgenX

**Comment by Palloxin** [comment]
no please, the long press button is like 0.8-1 seconds. don't tell me it is the same as the 2 steps. also, i am lazy and doing the 2 steps is annoying, i don't think i am the only one.

**Comment by natsuthelight** [comment]
the 2 steps take only 1 second for me. But I'm not saying not to put this feature but just  put a simplified filters after a long press.
